"""Hermes — ENV-конфиг и изменяемое runtime-состояние."""
import os

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_HERMES_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
HERMES_MODEL = os.getenv("HERMES_MODEL", "qwen2.5:3b")
HERMES_FALLBACK = os.getenv("HERMES_FALLBACK", "qwen2.5:0.5b")
HERMES_PROMPT_MODE = os.getenv("HERMES_PROMPT_MODE", "full").strip().lower()
HERMES_MAX_TOKENS = int(os.getenv("HERMES_MAX_TOKENS", "192"))
HERMES_ENABLE_FASTPATH = os.getenv("HERMES_ENABLE_FASTPATH", "0").lower() in ("1", "true", "yes")
HERMES_ENABLE_POST_VERIFY = os.getenv("HERMES_ENABLE_POST_VERIFY", "0").lower() in ("1", "true", "yes")
HERMES_ENABLE_CACHE = os.getenv("HERMES_ENABLE_CACHE", "0").lower() in ("1", "true", "yes")
HERMES_CACHE_TTL_SEC = int(os.getenv("HERMES_CACHE_TTL_SEC", "600"))
HERMES_ENABLE_MEMORY = os.getenv("HERMES_ENABLE_MEMORY", "0").lower() in ("1", "true", "yes")
HERMES_ENABLE_CONTEXT_COMPRESS = os.getenv("HERMES_ENABLE_CONTEXT_COMPRESS", "0").lower() in ("1", "true", "yes")
HERMES_COMPRESS_MAX_CHARS = int(os.getenv("HERMES_COMPRESS_MAX_CHARS", "2000"))
HERMES_ROUTING_POLICY = os.getenv("HERMES_ROUTING_POLICY", "default").strip().lower()
HERMES_PROMPT_PROFILE = os.getenv("HERMES_PROMPT_PROFILE", "").strip().lower()
HERMES_OLLAMA_TIMEOUT_SEC = float(os.getenv("HERMES_OLLAMA_TIMEOUT_SEC", "12"))
HERMES_OLLAMA_TOTAL_TIMEOUT_SEC = float(os.getenv("HERMES_OLLAMA_TOTAL_TIMEOUT_SEC", "14"))
HERMES_ENABLE_CONTEXT_PROFILE = os.getenv("HERMES_ENABLE_CONTEXT_PROFILE", "0").lower() in ("1", "true", "yes")
HERMES_OLLAMA_CTX_SHORT = int(os.getenv("HERMES_OLLAMA_CTX_SHORT", "2048"))
HERMES_OLLAMA_CTX_MEDIUM = int(os.getenv("HERMES_OLLAMA_CTX_MEDIUM", "4096"))
HERMES_OLLAMA_CTX_LONG = int(os.getenv("HERMES_OLLAMA_CTX_LONG", "8192"))
HERMES_OLLAMA_NUM_PREDICT = int(os.getenv("HERMES_OLLAMA_NUM_PREDICT", "96"))
HERMES_ENABLE_QUANT_MODEL = os.getenv("HERMES_ENABLE_QUANT_MODEL", "0").lower() in ("1", "true", "yes")
HERMES_MODEL_QUANT = os.getenv("HERMES_MODEL_QUANT", "qwen2.5:0.5b")
HERMES_OLLAMA_KEEP_ALIVE = os.getenv("HERMES_OLLAMA_KEEP_ALIVE", "10m")
HERMES_ENABLE_OLLAMA_PRELOAD = os.getenv("HERMES_ENABLE_OLLAMA_PRELOAD", "0").lower() in ("1", "true", "yes")
HERMES_ENABLE_GPU_OFFLOAD = os.getenv("HERMES_ENABLE_GPU_OFFLOAD", "0").lower() in ("1", "true", "yes")
HERMES_OLLAMA_NUM_GPU = int(os.getenv("HERMES_OLLAMA_NUM_GPU", "99"))
HERMES_OLLAMA_NUM_THREAD = int(os.getenv("HERMES_OLLAMA_NUM_THREAD", "6"))
HERMES_ENABLE_CONTEXT_HYGIENE = os.getenv("HERMES_ENABLE_CONTEXT_HYGIENE", "0").lower() in ("1", "true", "yes")

_intent_cache: dict[str, tuple[float, dict]] = {}
_preloaded_models: set[str] = set()
